### PR TITLE
Attempt an Unbox instance

### PR DESCRIPTION
**Pull request by istathar**
Instance for Unbox. This was harder that it should have been.

### CODE REVIEW

**Comment by istathar** [comment]
All I've done is add:

```haskell 
instance M.MVector MVector TimeStamp
instance G.Vector Vector TimeStamp
instance Unbox TimeStamp
```
(the first two apparently to satisfy the superclass requirements of the third) which seems insufficient. Sure enough this compiles, but with the following warnings:

```text
lib/Chrono/TimeStamp.hs:127:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘M.basicLength’, ‘M.basicUnsafeSlice’, ‘M.basicOverlaps’,
        ‘M.basicUnsafeNew’, ‘M.basicInitialize’,
        ‘M.basicUnsafeRead’, and ‘M.basicUnsafeWrite’
    • In the instance declaration for ‘M.MVector MVector TimeStamp’
lib/Chrono/TimeStamp.hs:128:10: warning: [-Wmissing-methods]
    • No explicit implementation for
        ‘G.basicUnsafeFreeze’, ‘G.basicUnsafeThaw’, ‘G.basicLength’,
        ‘G.basicUnsafeSlice’, and ‘G.basicUnsafeIndexM’
    • In the instance declaration for ‘G.Vector Vector TimeStamp’
```

in other words, I haven't actually done anything, which is true.

Our type is a `newtype` over Int64, so the `deriving` mechanism ought to be sufficient, but when I tried
```haskell
deriving instance M.MVector MVector TimeStamp
deriving instance G.Vector Vector TimeStamp
deriving instance Unbox TimeStamp
```
it rather exploded.

I think I'm supposed to do fancier things, but I really don't know anything about type families (?) or whatever is going on here. **vector** has always seemed a bit over-engineered to me, which probably means it's awesome and perfect once you know how to use it.

**Comment by istathar** [comment]
Worked around problem by manually writing out the instance for M.MVector MVector TimeStamp
and G.Vector Vector TimeStamp. I'm not super thrilled at having had to do that, but it compiles. I don't have a test that exercises this at all.

**Comment by luke-clifton** [comment]
I have a patch incoming (maybe tonight).

**Comment by istathar** [comment]
@luke-clifton Thanks! Also, I'll work your example into a test case and merge it in the morning.

**Comment by istathar** [comment]
Done. I'm tempted to move this code to a `Chrono.Instances` package or similar, but there's no rush on that.

**Pull request merged**
